from truco.src.strategies.random import RandomStrategy
from truco.src.strategies.conservative import ConservativeStrategy
from truco.src.strategies.aggressive import AggressiveStrategy
from truco.src.strategies.probabilistic import ProbabilisticStrategy
from truco.src.strategies.adaptive import AdaptiveStrategy
from truco.src.strategies.bluff import BluffStrategy
from truco.src.strategies.bayesian import BayesianStrategy
from truco.src.strategies.risk import RiskStrategy
from truco.src.strategies.hybrid import HybridStrategy
